# Generated by Django 4.0.4 on 2022-05-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpanel', '0007_metric_display_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='show_in_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metric',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', related_query_name='metric', to='reviewpanel.input'),
        ),
    ]
